services:
  # Database setup for development
   mysql-test:
    image: mysql:8.0
    container_name: mysql-test
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: locationsearch
      MYSQL_USER: localtionsearch
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"   
   
   mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: locationsearch
      MYSQL_USER: localtionsearch
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

networks:
  default:
    name: locationsearch-dev-network
