services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: locationsearch
      MYSQL_USER: localtionsearch
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    # volumes:
    #   - mysql_data:/var/lib/mysql

  nodejs:
    image: node:20
    container_name: nodejs
    restart: always
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    command: ["npm", "start"]
    depends_on:
      - mysql

volumes:
  mysql_data: