# Node.js
node_modules
npm-debug.log
yarn-debug.log
yarn-error.log
*.log
*.pid
*.seed
*.pid.lock

# Build artifacts
dist
temp
build

# Environment
.env
.env.*
!config/.env.*

# Git
.git
.gitignore

# Test files
coverage
.nyc_output
tests

# Docker
.dockerignore
Dockerfile
docker-compose*.yaml

# IDE
.idea
.vscode
*.sublime-workspace
*.sublime-project

# Misc
README.md
LICENSE
*.md
